Repository fatihtokus/scan2html, pull requests merged in 2025-08, with the labels that each got.

#178 Adding dark theme support #104
  src/frontend-app/src/App.css
  src/frontend-app/src/App.tsx
  src/frontend-app/src/index.css
Labels: Review effort 3/5

#179 new release v0.3.21
  plugin.yaml
Labels: Review effort 1/5

#180 Dark theme support to CodeDisplay component
  src/frontend-app/src/components/shared/CodeDisplay.tsx
Labels: Review effort 2/5

#188 Fix master
  internal/report/generator.go
Labels: Review effort 2/5

#191 Filter intelligence data
  internal/common/common.go
  internal/epss/downloader.go
  internal/report/generator.go
  release-candidate/plugin.yaml
Labels: Review effort 3/5
